title: "Yacqub Mohamed"
baseurl: ""
url: "https://yacyam.github.io"

theme: null
markdown: kramdown
permalink: /:categories/:title/

collections:
  publications:
    output: true
  research:
    output: true

# Navigation bar
nav:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Blog"
    url: /blog/
  - title: "About"
    url: /about/
